# Generated by Django 2.2.12 on 2020-12-02 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Task',
        ),
    ]
